MongooseIM/Chart.yaml, MongooseIM/templates/mongoose-cm.yaml, MongooseIM/templates/mongoose-sts.yaml, MongooseIM/templates/mongoose-svc-lb.yaml, MongooseIM/templates/mongoose-svc-nodeport.yaml, MongooseIM/values.yaml, MongoosePush/Chart.yaml, MongoosePush/values.yaml
This PR simply takes what we had on https://github.com/esl/mongooseim-kubernetes/tree/mim-helm and polishes it, so as much as that naming conventions are properly set, the latest version of MongooseIM is used, `values.yaml` is useful, and it all passes helm lint.
Next steps, coming incrementally in separate PRs, will be to document the persistent volumes, update the README, and pipeline creating the packages.
=> Helm ready

.circleci/config.yml
This PR introduces an automated pipeline to build the helm packages in CircleCI. It is for now a draft, that will become a common PR once #1 is merged, so that then this can be reviewed and merged.
This CircleCI configuration will basically run `helm lint` as a minimum testing for all pushes, as helm hub requires this linter to always pass. If what's being run is master, packages and the index will be rebuilt and pushed to an orphan branch called `packages`. This GitHub repo is at the moment configured to expose this `packages` branch as a github page. This github page link is what will be registered with helm hub, once everything is ready.
=> Build packages

MongooseIM/Chart.yaml, MongooseIM/mongooseim.toml, MongooseIM/templates/mongoose-cm.yaml, MongooseIM/templates/mongoose-svc-nodeport.yaml, MongooseIM/values.yaml, MongooseIM/vm.args
- Use the new 4.0.0 docker image with the TOML configuration file.
- Make it easier to change `mongooseim.toml` by including it in the config map. Also: process it with heml templates, so we could put some config options in `values.yaml`.
- Disable the `nodeport` service by default as in the typical setup only the load balancer is needed. What is more, our Google Cloud Platform setup prevents connection to higher port numbers that the nodeport service offers.
TO DO next:
- Clean up `values.yaml`
- Make it possible to run several clusters at the same time on the same cloud env by templating the `yaml` files for Kubernetes.
=> Update to MongooseIM 4.0.0 with extra config options 

MongooseIM/Chart.yaml, MongooseIM/configs/mongooseim.toml
```bash
➜  MongooseIM git:(update-to-5.1.0) ✗ kubectl get pods
NAME           READY   STATUS    RESTARTS   AGE
mongooseim-0   1/1     Running   0          3m32s
mongooseim-1   1/1     Running   0          2m21s
mongooseim-2   1/1     Running   0          75s
➜  MongooseIM git:(update-to-5.1.0) ✗ kubectl exec mongooseim-0 -- /usr/lib/mongooseim/bin/mongooseimctl mnesia running_db_nodes
['mongooseim@mongooseim-2.mongooseim.default.svc.cluster.local',
'mongooseim@mongooseim-1.mongooseim.default.svc.cluster.local',
'mongooseim@mongooseim-0.mongooseim.default.svc.cluster.local']
➜  MongooseIM git:(update-to-5.1.0) ✗ kubectl exec mongooseim-1 -- /usr/lib/mongooseim/bin/mongooseimctl mnesia running_db_nodes
['mongooseim@mongooseim-2.mongooseim.default.svc.cluster.local', …
```
=> Update mim to 5.1.0

MongooseIM/Chart.yaml, MongooseIM/configs/mongooseim.toml
Updating MIM version to 6.0.0.
```
januszjakubiec@MacBook-Pro-administrator-3 mongooseim % kubectl get pods
NAME           READY   STATUS    RESTARTS   AGE
mongooseim-0   1/1     Running   1          6h19m
mongooseim-1   1/1     Running   0          18m
mongooseim-2   1/1     Running   0          17m
januszjakubiec@MacBook-Pro-administrator-3 etc % kubectl exec mongooseim-1 -- /usr/lib/mongooseim/bin/mongooseimctl mnesia systemInfo --keys '["running_db_nodes"]'
{
"data" : {
"mnesia" : {
"systemInfo" : [
{
"result" : [
"mongooseim@mongooseim-2.mongooseim.default.svc.cluster.local",
"mongooseim@mongooseim-0.mongooseim.default.svc.cluster.local",
"mongooseim@mongooseim-1.mongooseim.default.svc.cluster.local"
],
"key" : "running_db_nodes"
}
]
}
}
}
```
=> Update MIM to 6.0.0

MongooseIM/Chart.yaml, MongooseIM/README.md, MongooseIM/templates/NOTES.txt, MongooseIM/templates/mongoose-sts.yaml, MongooseIM/templates/mongoose-svc-lb.yaml, MongooseIM/templates/mongoose-svc.yaml, MongooseIM/values.yaml
The goal is to update the chart for a production-ready setup.
Main changes:
- Expose GraphQL API
- Provide TLS certificates with secrets
- Enable rolling update
- Add `nodeSelector` and `loadBalancerAnnotations`
=> Update various configuration options

MongooseIM/README.md, MongooseIM/configs/mongooseim.toml, MongooseIM/templates/NOTES.txt, MongooseIM/templates/mongoose-sts.yaml, MongooseIM/values.yaml
Make it possible (and easy) to configure MongooseIM without Mnesia and persistent volumes.
The default configuration still uses Mnesia, and it can be still installed easily.
For example, I tested the following setup:
```
$ helm install mim-test MongooseIM --set replicaCount=3 --set image.tag=latest
$ helm upgrade mim-test MongooseIM --set replicaCount=3 --set image.tag=latest
$ helm uninstall mim-test
$ kubectl delete pvc --all
```
Thanks to the randomly generated `rolloutId`, the second command triggered a rolling upgrade, starting with the last node. After the upgrade the Psi+ XMPP client could still connect, and all nodes were still clustered.
Using RDBMS is easier thanks to config templating:
```
$ helm install mim-test MongooseIM --set replicaCount=3 --set image.tag=latest --set …
```
=> Configure MongooseIM with RDBMS and CETS

MongooseIM/templates/mongoose-sts.yaml, MongooseIM/templates/mongoose-svc-lb.yaml, MongooseIM/templates/mongoose-svc.yaml
This is needed for web clients, because browsers enforce wss if the initial page is served over HTTPS.
=> Open port 5285 for secure ws/bosh

MongooseIM/templates/mongoose-sts.yaml
It was already in `values.yaml`
=> Add missing template for pull policy

MongooseIM/README.md, MongooseIM/templates/mongoose-cm.yaml
This PR introduces a new configuration value `appConfig`. Setting this value to an `app.config` file content will enable providing custom configuration for e.g. logger or metrics reporter. If not set, no entry in configmap will be created and the one from docker image will be used.
Tested locally on minikube.
=> Add option to provide app.config file

MongooseIM/configs/mongooseim.toml
It should be the same as for `mod_privacy`.
=> Add missing backend option for mod_blocking

MongooseIM/configs/mongooseim.toml
This PR removes the `services.service_admin_extra` entry from the template configuration file. This change is necessary because this entry is no longer relevant after the removal of legacy CLI commands.
Relates to: https://github.com/esl/MongooseIM/pull/4160
=> Remove service_admin_extra

MongooseIM/configs/vm.args, MongooseIM/templates/mongoose-sts.yaml, MongooseIM/templates/mongoose-svc.yaml
Requires https://github.com/esl/MongooseIM/pull/4179
How to test (clone, checkout this branch first):
```
helm install test-mim MongooseIM --set replicaCount=10 --set image.tag=PR-4179 --set persistentDatabase=rdbms --set rdbms.username=mongooseim --set rdbms.database=mongooseim --set volatileDatabase=cets
```
(only PR-4163 works with this build because of new config options for wait_for_dns).
Nodes are joined:
```
kubectl exec -it mongooseim-0 -- mongooseimctl cets systemInfo
```
And logs are cleaner:
```
kubectl logs mongooseim-0
```
Upgrades should work too:
```
helm upgrade mim-test MongooseIM --set replicaCount=10 --set image.tag=PR-4179 --set persistentDatabase=rdbms --set rdbms.username=mongooseim --set rdbms.database=mongooseim --set volatileDatabase=cets --set …
```
=> Custom epmd to avoid race conditions in DNS name resolutions

MongooseIM/Chart.yaml
Version is updated to `0.4.0` because there is new functionality - config templating and the DB-related options.
Chart tested manually.
=> Update MongooseIM version to 6.2.0

MongooseIM/README.md, MongooseIM/templates/mongoose-sts.yaml
This PR adds resource definitions to the MongooseIM stateful set container spec. If `resources` are specified in `values.yaml`, then `requests` must be provided, while `limits` may be provided.
=> Allow to define MongooseIM resource requests and limits

Amoc/Chart.yaml, Amoc/templates/sts.yaml, Amoc/values.yaml, test/mim_kind_SUITE.erl
Changes include:
- AMOC chart. We use it to connect users to MIM.
- Test, checking sessionCount is updated correctly on netsplit (we temporary disable raising an error in this test). 
Addresses MIM-2152.
=> Testing sessionCount after node restarts

MongooseIM/configs/mongooseim.toml, MongooseIM/templates/mongoose-sts.yaml, MongooseIM/templates/mongoose-svc-lb.yaml, MongooseIM/templates/mongoose-svc-nodeport.yaml, MongooseIM/templates/mongoose-svc.yaml
As in the title. The idea is to enable the so called "legacy" TLS, which really should have been the way all along.
=> Add 5223 port for full-TLS listener

test/mim_kind_SUITE.erl
Tests that PR for MongooseIM: https://github.com/esl/MongooseIM/pull/4234
It is a pretty slow CI task, so merging task splitting PR first could be useful: https://github.com/esl/MongooseHelm/pull/37 
Here is how logs look like during k8s cluster upgrade (long prevent_overlapped_partitions loops are gone):
```
when=2024-03-06T13:20:55.502653+00:00 level=warning what=nodeup pid=<0.429.0> at=cets_discovery:handle_nodeup/2:607 time_since_startup_in_milliseconds=227 connected_nodes=2 remote_node=mongooseim@mongooseim-1.mongooseim.default.svc.cluster.local 
when=2024-03-06T13:20:55.505088+00:00 level=warning what=nodeup pid=<0.429.0> at=cets_discovery:handle_nodeup/2:607 time_since_startup_in_milliseconds=230 connected_nodes=3 remote_node=mongooseim@mongooseim-0.mongooseim.default.svc.cluster.lo …
```
=> Dist blocker

test/mim_kind_SUITE.erl
This command was making the tests flaky.
The most likely reason is that there were duplicate instances of MIM running with the same node name, because k8s resources were not cleaned up yet.
MIM logs confirm that:
```
when=2024-03-29T07:51:27.521675+00:00 level=warning what=node_reconnects pid=<0.428.0> at=cets_discovery:handle_receive_start_time/3:681 text="Netsplit recovery. The remote node has been connected to us before." start_time=1711698687360 remote_node=mongooseim@mongooseim-0.mongooseim.default.svc.cluster.local
when=2024-03-29T07:51:27.532234+00:00 level=error what=already_added pid=<0.544.0> at=cets:add_servers/2:692 servers=[<30917.544.0>,<30918.544.0>] pids=[<30917.544.0>] already_added_servers=[<30917.544.0>]
```
If we need to test instant restarts, we can do this with …
=> Don't delete pod with '--force'

MongooseIM/templates/mongoose-svc-lb.yaml
Open s2s port by default on the load-balancer
=> Add s2s port to load balancer

MongooseIM/configs/mongooseim.toml, MongooseIM/templates/mongoose-sts.yaml, MongooseIM/templates/mongoose-svc.yaml, MongooseIM/values.yaml, README.md
- We are moving the docker image from [mongooseim/mongooseim](https://hub.docker.com/repository/docker/mongooseim/mongooseim/general) (free tier) to [erlangsolutions/mongooseim](https://hub.docker.com/repository/docker/erlangsolutions/mongooseim/general) (paid tier).
- `mongoose_metrics` are replaced with `mongoose_instrument`, which has different config options. Enable `prometheus` and `log` handlers, just like in the default `prod` config file.
=> Update docker repo and the instrumentation config

MongooseIM/Chart.yaml, MongooseIM/templates/NOTES.txt, test/mim_kind_SUITE.erl
This PR updates the MIM chart version to 6.3.2, as well as the copyright year to 2025.
It also fixes the issue with the `amoc_arsenal_xmpp` path in the tests.
```
% kubectl get pods
NAME           READY   STATUS    RESTARTS   AGE
mongooseim-0   1/1     Running   0          40s
mongooseim-1   1/1     Running   0          2m14s
mongooseim-2   1/1     Running   0          102s
% kubectl exec mongooseim-1 -- /usr/lib/mongooseim/bin/mongooseimctl mnesia systemInfo --keys '["running_db_nodes"]'
{
"data" : {
"mnesia" : {
"systemInfo" : [
{
"result" : [
"mongooseim@mongooseim-0.mongooseim.default.svc.cluster.local",
"mongooseim@mongooseim-2.mongooseim.default.svc.cluster.local",
"mongooseim@mongooseim-1.mongooseim.default.svc.cluster.local"
],
"key" : "running_db_nodes"
}
]
}
}
}
% kubectl exec …
```
=> Update MIM to 6.3.2

.gitignore, MongooseIM/Chart.yaml, test/mim_kind_SUITE.erl
This PR updates the MongooseIM Helm chart to version 6.3.3 and also includes the following changes:
1. Temporarily sets the testing tag to `6.3.3` instead of `latest`, since the current master build includes updates that require changes to the config file. This PR focuses on version 6.3.3. Updating the config and reverting the tag back to `latest` can be done in a separate PR.
2. Modifies the way the PostgreSQL password is provided to the Helm container, as the previous method that was using the `$POSTGRES_PASSWORD` environment variable no longer works. The PostgreSQL password is provided via a Kubernetes Secret, which is created by the Helm chart [here](https://github.com/bitnami/charts/blob/main/bitnami/postgresql/templates/secrets.yaml#L45-L50). The password is retrieved as shown in …
=> Update MIM to 6.3.3

MongooseIM/Chart.yaml, MongooseIM/configs/mongooseim.toml, test/mim_kind_SUITE.erl
This PR updates the MongooseIM Helm chart to use version 6.4.0.
```
% kubectl exec mongooseim-1 -- /usr/lib/mongooseim/bin/mongooseimctl server status
{
"data" : {
"server" : {
"status" : {
"version" : "6.4.0",
"statusCode" : "RUNNING",
"message" : "The node 'mongooseim@mongooseim-1.mongooseim.default.svc.cluster.local' is started. Status: started. MongooseIM 6.4.0 is running in that node.",
"commitHash" : ""
}
}
}
}
% kubectl exec --stdin --tty mongooseim-0 -- /bin/bash
root@mongooseim-0:/# ./lib/mongooseim/bin/mongooseim version
..';:cc:,                                   
,ooooooo''l:'                                
;ooooooooool.                               
.oooooooc,.                                 
.oooooo:                                    
,oooooo, …
```
=> Update MIM to 6.4.0
